[package]
name = "magikitten"
description = "Easy Fiat-Shamirization using Meow"
repository = "https://github.com/cronokirby/magikitten"
license = "MIT"
version = "0.2.0"
edition = "2021"


[dependencies]
ck-meow = "0.1.0"
rand_core = "0.6.3"
